/*
 Copyright (c) 2010 Brandon Aaron (http://brandonaaron.net)
 Licensed under the MIT License (LICENSE.txt).

 Thanks to: http://adomas.org/javascript-mouse-wheel/ for some pointers.
 Thanks to: Mathias Bank(http://www.mathias-bank.de) for a scope bug fix.
 Thanks to: Seamus Leahy for adding deltaX and deltaY

 Version: 3.0.4

 Requires: 1.2.2+
*/
(function(g,f){var a={};f.$widgetkit={lazyloaders:{},load:function(c){a[c]||(a[c]=g.getScript(c));return a[c]},lazyload:function(a){a=a||document;g("[data-widgetkit]",a).each(function(){var a=g(this),c=a.data("widgetkit"),b=a.data("options")||{};!a.data("wk-loaded")&&$widgetkit.lazyloaders[c]&&($widgetkit.lazyloaders[c](a,b),a.data("wk-loaded",!0))})}};g(function(){$widgetkit.lazyload()});for(var c=document.createElement("div"),b=c.style,c=!1,d=["-webkit-","-moz-","-o-","-ms-","-khtml-"],e=["Webkit",
"Moz","O","ms","Khtml"],h="",i=0;i<e.length;i++)if(""===b[e[i]+"Transition"]){c=e[i]+"Transition";h=d[i];break}$widgetkit.prefix=h;b=$widgetkit;c=(d=c)&&"WebKitCSSMatrix"in window&&"m11"in new WebKitCSSMatrix&&!navigator.userAgent.match(/Chrome/i);e=document.createElement("canvas");e=!(!e.getContext||!e.getContext("2d"));b.support={transition:d,css3d:c,canvas:e};$widgetkit.css3=function(a){a=a||{};a.transition&&(a[h+"transition"]=a.transition);a.transform&&(a[h+"transform"]=a.transform);a["transform-origin"]&&
(a[h+"transform-origin"]=a["transform-origin"]);return a};c=null})(jQuery,window);(function(g){var f;a:{try{f=parseInt(navigator.appVersion.match(/MSIE (\d\.\d)/)[1],10);break a}catch(a){}f=!1}f&&9>f&&(g(document).ready(function(){g("body").addClass("wk-ie wk-ie"+f)}),g.each("abbr article aside audio canvas details figcaption figure footer header hgroup mark meter nav output progress section summary time video".split(" "),function(){document.createElement(this)}))})(jQuery);
(function(g,f){f.$widgetkit.trans={__data:{},addDic:function(a){g.extend(this.__data,a)},add:function(a,c){this.__data[a]=c},get:function(a){if(!this.__data[a])return a;var c=1==arguments.length?[]:Array.prototype.slice.call(arguments,1);return this.printf(String(this.__data[a]),c)},printf:function(a,c){if(!c)return a;var b="",d=a.split("%s");if(1==d.length)return a;for(var e=0;e<c.length;e++)d[e].lastIndexOf("%")==d[e].length-1&&e!=c.length-1&&(d[e]+="s"+d.splice(e+1,1)[0]),b+=d[e]+c[e];return b+
d[d.length-1]}}})(jQuery,window);
(function(g){g.easing.jswing=g.easing.swing;g.extend(g.easing,{def:"easeOutQuad",swing:function(f,a,c,b,d){return g.easing[g.easing.def](f,a,c,b,d)},easeInQuad:function(f,a,c,b,d){return b*(a/=d)*a+c},easeOutQuad:function(f,a,c,b,d){return-b*(a/=d)*(a-2)+c},easeInOutQuad:function(f,a,c,b,d){return 1>(a/=d/2)?b/2*a*a+c:-b/2*(--a*(a-2)-1)+c},easeInCubic:function(f,a,c,b,d){return b*(a/=d)*a*a+c},easeOutCubic:function(f,a,c,b,d){return b*((a=a/d-1)*a*a+1)+c},easeInOutCubic:function(f,a,c,b,d){return 1>
(a/=d/2)?b/2*a*a*a+c:b/2*((a-=2)*a*a+2)+c},easeInQuart:function(f,a,c,b,d){return b*(a/=d)*a*a*a+c},easeOutQuart:function(f,a,c,b,d){return-b*((a=a/d-1)*a*a*a-1)+c},easeInOutQuart:function(f,a,c,b,d){return 1>(a/=d/2)?b/2*a*a*a*a+c:-b/2*((a-=2)*a*a*a-2)+c},easeInQuint:function(f,a,c,b,d){return b*(a/=d)*a*a*a*a+c},easeOutQuint:function(f,a,c,b,d){return b*((a=a/d-1)*a*a*a*a+1)+c},easeInOutQuint:function(f,a,c,b,d){return 1>(a/=d/2)?b/2*a*a*a*a*a+c:b/2*((a-=2)*a*a*a*a+2)+c},easeInSine:function(f,a,
c,b,d){return-b*Math.cos(a/d*(Math.PI/2))+b+c},easeOutSine:function(f,a,c,b,d){return b*Math.sin(a/d*(Math.PI/2))+c},easeInOutSine:function(f,a,c,b,d){return-b/2*(Math.cos(Math.PI*a/d)-1)+c},easeInExpo:function(f,a,c,b,d){return 0==a?c:b*Math.pow(2,10*(a/d-1))+c},easeOutExpo:function(f,a,c,b,d){return a==d?c+b:b*(-Math.pow(2,-10*a/d)+1)+c},easeInOutExpo:function(f,a,c,b,d){return 0==a?c:a==d?c+b:1>(a/=d/2)?b/2*Math.pow(2,10*(a-1))+c:b/2*(-Math.pow(2,-10*--a)+2)+c},easeInCirc:function(f,a,c,b,d){return-b*
(Math.sqrt(1-(a/=d)*a)-1)+c},easeOutCirc:function(f,a,c,b,d){return b*Math.sqrt(1-(a=a/d-1)*a)+c},easeInOutCirc:function(f,a,c,b,d){return 1>(a/=d/2)?-b/2*(Math.sqrt(1-a*a)-1)+c:b/2*(Math.sqrt(1-(a-=2)*a)+1)+c},easeInElastic:function(f,a,c,b,d){var f=1.70158,e=0,h=b;if(0==a)return c;if(1==(a/=d))return c+b;e||(e=0.3*d);h<Math.abs(b)?(h=b,f=e/4):f=e/(2*Math.PI)*Math.asin(b/h);return-(h*Math.pow(2,10*(a-=1))*Math.sin((a*d-f)*2*Math.PI/e))+c},easeOutElastic:function(f,a,c,b,d){var f=1.70158,e=0,h=b;
if(0==a)return c;if(1==(a/=d))return c+b;e||(e=0.3*d);h<Math.abs(b)?(h=b,f=e/4):f=e/(2*Math.PI)*Math.asin(b/h);return h*Math.pow(2,-10*a)*Math.sin((a*d-f)*2*Math.PI/e)+b+c},easeInOutElastic:function(f,a,c,b,d){var f=1.70158,e=0,h=b;if(0==a)return c;if(2==(a/=d/2))return c+b;e||(e=d*0.3*1.5);h<Math.abs(b)?(h=b,f=e/4):f=e/(2*Math.PI)*Math.asin(b/h);return 1>a?-0.5*h*Math.pow(2,10*(a-=1))*Math.sin((a*d-f)*2*Math.PI/e)+c:0.5*h*Math.pow(2,-10*(a-=1))*Math.sin((a*d-f)*2*Math.PI/e)+b+c},easeInBack:function(f,
a,c,b,d,e){void 0==e&&(e=1.70158);return b*(a/=d)*a*((e+1)*a-e)+c},easeOutBack:function(f,a,c,b,d,e){void 0==e&&(e=1.70158);return b*((a=a/d-1)*a*((e+1)*a+e)+1)+c},easeInOutBack:function(f,a,c,b,d,e){void 0==e&&(e=1.70158);return 1>(a/=d/2)?b/2*a*a*(((e*=1.525)+1)*a-e)+c:b/2*((a-=2)*a*(((e*=1.525)+1)*a+e)+2)+c},easeInBounce:function(f,a,c,b,d){return b-g.easing.easeOutBounce(f,d-a,0,b,d)+c},easeOutBounce:function(f,a,c,b,d){return(a/=d)<1/2.75?b*7.5625*a*a+c:a<2/2.75?b*(7.5625*(a-=1.5/2.75)*a+0.75)+
c:a<2.5/2.75?b*(7.5625*(a-=2.25/2.75)*a+0.9375)+c:b*(7.5625*(a-=2.625/2.75)*a+0.984375)+c},easeInOutBounce:function(f,a,c,b,d){return a<d/2?0.5*g.easing.easeInBounce(f,2*a,0,b,d)+c:0.5*g.easing.easeOutBounce(f,2*a-d,0,b,d)+0.5*b+c}})})(jQuery);
(function(g){function f(a){var b=a||window.event,d=[].slice.call(arguments,1),e=0,f=0,i=0,a=g.event.fix(b);a.type="mousewheel";a.wheelDelta&&(e=a.wheelDelta/120);a.detail&&(e=-a.detail/3);i=e;void 0!==b.axis&&b.axis===b.HORIZONTAL_AXIS&&(i=0,f=-1*e);void 0!==b.wheelDeltaY&&(i=b.wheelDeltaY/120);void 0!==b.wheelDeltaX&&(f=-1*b.wheelDeltaX/120);d.unshift(a,e,f,i);return g.event.handle.apply(this,d)}var a=["DOMMouseScroll","mousewheel"];g.event.special.mousewheel={setup:function(){if(this.addEventListener)for(var c=
a.length;c;)this.addEventListener(a[--c],f,!1);else this.onmousewheel=f},teardown:function(){if(this.removeEventListener)for(var c=a.length;c;)this.removeEventListener(a[--c],f,!1);else this.onmousewheel=null}};g.fn.extend({mousewheel:function(a){return a?this.bind("mousewheel",a):this.trigger("mousewheel")},unmousewheel:function(a){return this.unbind("mousewheel",a)}})})(jQuery);
(function(g){var f=g.support;var a=document.createElement("INPUT");a.type="file";if(a="files"in a)a=new XMLHttpRequest,a=!(!a||!("upload"in a&&"onprogress"in a.upload))&&!!window.FormData;f.ajaxupload=a;g.support.ajaxupload&&g.event.props.push("dataTransfer");g.fn.uploadOnDrag=function(a){return!g.support.ajaxupload?this:this.each(function(){var b=g(this),d=g.extend({action:"",single:!1,method:"POST",params:{},loadstart:function(){},load:function(){},loadend:function(){},progress:function(){},complete:function(){},
allcomplete:function(){},readystatechange:function(){}},a);b.on("drop",function(a){function c(a,b){for(var d=new FormData,e=new XMLHttpRequest,f=0,h;h=a[f];f++)d.append("files[]",h);for(var i in b.params)d.append(i,b.params[i]);e.upload.addEventListener("progress",function(a){b.progress(100*(a.loaded/a.total),a)},!1);e.addEventListener("loadstart",function(a){b.loadstart(a)},!1);e.addEventListener("load",function(a){b.load(a)},!1);e.addEventListener("loadend",function(a){b.loadend(a)},!1);e.addEventListener("error",
function(a){b.error(a)},!1);e.addEventListener("abort",function(a){b.abort(a)},!1);e.open(b.method,b.action,!0);e.onreadystatechange=function(){b.readystatechange(e);if(4==e.readyState){var a=e.responseText;if("json"==b.type)try{a=g.parseJSON(a)}catch(c){a=!1}b.complete(a,e)}};e.send(d)}a.stopPropagation();a.preventDefault();var b=a.dataTransfer.files;if(d.single){var f=a.dataTransfer.files.length,j=0,k=d.complete;d.complete=function(a,e){j+=1;k(a,e);j<f?c([b[j]],d):d.allcomplete()};c([b[0]],d)}else c(b,
d)}).on("dragover",function(a){a.stopPropagation();a.preventDefault()})})};g.fn.ajaxform=function(a){return!g.support.ajaxupload?this:this.each(function(){var b=g(this),d=g.extend({action:b.attr("action"),method:b.attr("method"),loadstart:function(){},load:function(){},loadend:function(){},progress:function(){},complete:function(){},readystatechange:function(){}},a);b.on("submit",function(a){a.preventDefault();var a=new FormData(this),b=new XMLHttpRequest;a.append("formdata","1");b.upload.addEventListener("progress",
function(a){d.progress(100*(a.loaded/a.total),a)},!1);b.addEventListener("loadstart",function(a){d.loadstart(a)},!1);b.addEventListener("load",function(a){d.load(a)},!1);b.addEventListener("loadend",function(a){d.loadend(a)},!1);b.addEventListener("error",function(a){d.error(a)},!1);b.addEventListener("abort",function(a){d.abort(a)},!1);b.open(d.method,d.action,!0);b.onreadystatechange=function(){d.readystatechange(b);if(4==b.readyState){var a=b.responseText;if("json"==d.type)try{a=g.parseJSON(a)}catch(c){a=
!1}d.complete(a,b)}};b.send(a)})})}})(jQuery);
